#!/usr/bin/env bash
# Simple app launcher that shows a list of options and handles them by on a case basis

options=$(
    echo " Lock"
    echo "󰤄 Sleep"
    echo "⏻ Power Off"
    echo " Reboot"
    echo "󰗽 Logout"
)

selection=$(pkill fuzzel || echo -e "$options" | fuzzel --dmenu -i -p "Logout Menu")
if [[ -z $selection ]]; then
    exit
fi

case "$selection" in
    " Lock")
        sleep 0.5
        loginctl lock-session
        ;;
    "󰤄 Sleep")
        systemctl suspend
        ;;
    "⏻ Power Off")
        systemctl poweroff
        ;;
    " Reboot")
        systemctl reboot
        ;;
    "󰗽 Logout")
        loginctl terminate-user ''
        ;;
    *)
        echo "how did we get here"
        ;;
esac
